# Generated by Django 3.0.7 on 2022-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=20)),
                ('commentInfo', models.TextField(blank=True, max_length=84)),
            ],
        ),
    ]
