# Generated by Django 3.0.7 on 2022-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentInfo',
            field=models.TextField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='comments',
            name='service',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
